# Generated by Django 4.1.13 on 2025-09-02 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ENTRENADOR", "Entrenador"),
                    ("CLIENTE", "Cliente"),
                    ("NUTRICIONISTA", "nutricionista"),
                ],
                max_length=20,
                verbose_name="Rol",
            ),
        ),
    ]
