# Generated by Django 5.2 on 2025-09-22 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ejercicios", "0001_initial"),
        ("entrenamiento", "0004_exercise_warmup_alter_workoutexercise_exercise"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Exercise",
        ),
        migrations.DeleteModel(
            name="Warmup",
        ),
    ]
