# Generated by Django 5.2 on 2025-09-24 23:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nombre del Ejercicio"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "video_url",
                    models.URLField(blank=True, verbose_name="URL del Video"),
                ),
                (
                    "muscle_group",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Grupo Muscular"
                    ),
                ),
                (
                    "equipment",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Equipamiento"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Warmup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Nombre del Calentamiento"
                    ),
                ),
                (
                    "series_reps",
                    models.CharField(max_length=50, verbose_name="Series/Reps"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notas")),
                (
                    "video_url",
                    models.URLField(blank=True, verbose_name="URL del Video"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("inferior", "Tren Inferior"),
                            ("superior", "Tren Superior"),
                        ],
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TrainingPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Nombre del Plan"),
                ),
                ("start_date", models.DateField(verbose_name="Fecha de Inicio")),
                ("end_date", models.DateField(verbose_name="Fecha de Fin")),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Activo"), ("completed", "Completado")],
                        default="active",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notas")),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_plans",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "trainer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_plans",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Entrenador",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Workout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "week_number",
                    models.PositiveIntegerField(verbose_name="Número de Semana"),
                ),
                (
                    "day_of_week",
                    models.PositiveIntegerField(
                        verbose_name="Día de la Semana (1=Lunes)"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=200, verbose_name="Título del Entrenamiento"
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha del Entrenamiento"
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workouts",
                        to="entrenamiento.trainingplan",
                        verbose_name="Plan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkoutExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sets", models.PositiveIntegerField(verbose_name="Series")),
                (
                    "reps_target",
                    models.CharField(
                        max_length=50, verbose_name="Repeticiones Objetivo"
                    ),
                ),
                (
                    "rir_target",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="RIR Objetivo"
                    ),
                ),
                (
                    "rpe_target",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="RPE Objetivo"
                    ),
                ),
                (
                    "rest_period_seconds",
                    models.PositiveIntegerField(
                        default=60, verbose_name="Descanso (segundos)"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notas")),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Orden en el Workout"
                    ),
                ),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="entrenamiento.exercise",
                        verbose_name="Ejercicio",
                    ),
                ),
                (
                    "workout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercises",
                        to="entrenamiento.workout",
                        verbose_name="Entrenamiento",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ExerciseLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_completed",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Completado"
                    ),
                ),
                (
                    "weight_lifted_kg",
                    models.FloatField(verbose_name="Peso Levantado (kg)"),
                ),
                (
                    "reps_completed",
                    models.PositiveIntegerField(
                        verbose_name="Repeticiones Completadas"
                    ),
                ),
                (
                    "rir_actual",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="RIR Real"
                    ),
                ),
                (
                    "rpe_actual",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="RPE Real"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, verbose_name="Notas del Cliente"),
                ),
                (
                    "video_log",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="logs/videos/",
                        verbose_name="Video de Registro",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("completed", "Completado"),
                            ("half", "A Medias"),
                            ("not_completed", "No Completado"),
                        ],
                        default="completed",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "workout_exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="entrenamiento.workoutexercise",
                        verbose_name="Ejercicio del Plan",
                    ),
                ),
            ],
        ),
    ]
