# Generated by Django 4.1.13 on 2025-09-02 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entrenamiento", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workout",
            name="date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha del Entrenamiento"
            ),
        ),
    ]
