# Generated by Django 5.2 on 2025-09-25 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entrenamiento", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workoutexercise",
            name="video_required",
            field=models.BooleanField(default=False, verbose_name="Video Requerido"),
        ),
    ]
