# Generated by Django 4.1.13 on 2025-09-08 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entrenamiento", "0002_workout_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingplan",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Notas"),
        ),
    ]
