# Generated by Django 5.2 on 2025-09-22 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entrenamiento", "0003_trainingplan_notes"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nombre del Ejercicio"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "video_url",
                    models.URLField(blank=True, verbose_name="URL del Video"),
                ),
                (
                    "muscle_group",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Grupo Muscular"
                    ),
                ),
                (
                    "equipment",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Equipamiento"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Warmup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Nombre del Calentamiento"
                    ),
                ),
                (
                    "series_reps",
                    models.CharField(max_length=50, verbose_name="Series/Reps"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notas")),
                (
                    "video_url",
                    models.URLField(blank=True, verbose_name="URL del Video"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("inferior", "Tren Inferior"),
                            ("superior", "Tren Superior"),
                        ],
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="workoutexercise",
            name="exercise",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="entrenamiento.exercise",
                verbose_name="Ejercicio",
            ),
        ),
    ]
